export const CATEGORY_NAMES = [
  'COVID-19',
  'Alcoholism',
  'Allergy',
  'Alzheimers',
  'Anti Fungal',
  'Anti Viral',
  'Anti-Depressants',
  'Anti-Inflammatory',
  'Antibacterial',
  'Antibiotics',
  'Antiparasitic',
  'Arthritis',
  'Asthma',
  'Birth Control',
  'Blood Pressure',
  'Cancer',
  'Cardiovascular',
  'Cholesterol',
  'Diabetes',
  'Diuretics',
  'Erectile Dysfunction',
  'Eye Drop',
  'Gastro Health',
] as const

export type SeedProduct = {
  name: string
  genericName: string
  category: string
  description: string
  price: number
  unit: 'pill' | 'sachet' | 'bottle'
  dosageOptions: string[]
  image: string
  discount: number
  inStock: boolean
}

export const SEED_PRODUCTS: Array<SeedProduct> = [
  {
    name: 'Viagra',
    genericName: 'Sildenafil Citrate',
    category: 'Erectile Dysfunction',
    description:
      'Fast-acting support for erectile dysfunction, formulated for dependable performance and physician-guided use.',
    price: 0.36,
    unit: 'pill',
    dosageOptions: ['25mg', '50mg', '100mg', '120mg', '130mg', '150mg', '200mg'],
    image: '/products/viagra.svg',
    discount: 33,
    inStock: true,
  },
  {
    name: 'Cialis',
    genericName: 'Tadalafil',
    category: 'Erectile Dysfunction',
    description: 'Long-duration erectile dysfunction treatment option designed for flexibility and confidence.',
    price: 1.07,
    unit: 'pill',
    dosageOptions: ['10mg', '20mg', '40mg', '60mg', '80mg'],
    image: '/products/cialis.svg',
    discount: 33,
    inStock: true,
  },
  {
    name: 'Kamagra Oral Jelly',
    genericName: 'Sildenafil Citrate',
    category: 'Erectile Dysfunction',
    description: 'Convenient sachet-based oral jelly format for patients seeking an alternative to standard tablets.',
    price: 2.3,
    unit: 'sachet',
    dosageOptions: ['100mg'],
    image: '/products/kamagra-jelly.svg',
    discount: 33,
    inStock: true,
  },
  {
    name: 'Kamagra',
    genericName: 'Sildenafil Citrate',
    category: 'Erectile Dysfunction',
    description: 'Cost-effective sildenafil option with reliable dosage and quality-controlled formulation.',
    price: 1.42,
    unit: 'pill',
    dosageOptions: ['100mg'],
    image: '/products/kamagra.svg',
    discount: 33,
    inStock: true,
  },
  {
    name: 'Cetirizine',
    genericName: 'Cetirizine Hydrochloride',
    category: 'Allergy',
    description: 'Daily antihistamine relief for sneezing, itchy eyes, and seasonal allergy symptoms.',
    price: 0.52,
    unit: 'pill',
    dosageOptions: ['5mg', '10mg'],
    image: '/products/cetirizine.svg',
    discount: 20,
    inStock: true,
  },
  {
    name: 'Amlodipine',
    genericName: 'Amlodipine Besylate',
    category: 'Blood Pressure',
    description: 'Calcium channel blocker to support healthy blood pressure management under medical supervision.',
    price: 0.68,
    unit: 'pill',
    dosageOptions: ['2.5mg', '5mg', '10mg'],
    image: '/products/amlodipine.svg',
    discount: 20,
    inStock: true,
  },
  {
    name: 'Metformin',
    genericName: 'Metformin Hydrochloride',
    category: 'Diabetes',
    description: 'Frontline diabetes therapy supporting glucose control and long-term metabolic health.',
    price: 0.49,
    unit: 'pill',
    dosageOptions: ['500mg', '850mg', '1000mg'],
    image: '/products/metformin.svg',
    discount: 25,
    inStock: true,
  },
  {
    name: 'Omeprazole',
    genericName: 'Omeprazole',
    category: 'Gastro Health',
    description: 'Acid-reducing therapy to help control reflux and improve digestive comfort.',
    price: 0.74,
    unit: 'pill',
    dosageOptions: ['10mg', '20mg', '40mg'],
    image: '/products/omeprazole.svg',
    discount: 20,
    inStock: true,
  },
  {
    name: 'Moxifloxacin Eye Drop',
    genericName: 'Moxifloxacin',
    category: 'Eye Drop',
    description: 'Broad-spectrum ophthalmic antibacterial drops for clinically directed eye infection care.',
    price: 7.8,
    unit: 'bottle',
    dosageOptions: ['5ml'],
    image: '/products/eye-drop.svg',
    discount: 15,
    inStock: true,
  },
]
