export const CATEGORY_LIST = [
  'COVID-19',
  'Alcoholism',
  'Allergy',
  'Alzheimers',
  'Anti Fungal',
  'Anti Viral',
  'Anti-Depressants',
  'Anti-Inflammatory',
  'Antibacterial',
  'Antibiotics',
  'Antiparasitic',
  'Arthritis',
  'Asthma',
  'Birth Control',
  'Blood Pressure',
  'Cancer',
  'Cardiovascular',
  'Cholesterol',
  'Diabetes',
  'Diuretics',
  'Erectile Dysfunction',
  'Eye Drop',
  'Gastro Health',
] as const
